#ifndef _CE_CONFIG_BASE_H_
#define _CE_CONFIG_BASE_H_

//- Version -
#define CE_VERSION_MAJOR 0
#define CE_VERSION_MINOR 01

#define CE_BASE_USEPOSIXTHREAD 1
#define CE_BASE_USEWINTHREAD 0

#define CE_BASE_USEPOSIXSOCKET 1
#define CE_BASE_USEWINSOCKET 0

#endif
