#ifndef _CE_SCANCODE_H_
#define _CE_SCANCODE_H_

//- All values follow the USB Scan Code Set as taken from <http://www.usb.org/developers/devclass_docs/Hut1_12v2.pdf> -

namespace ce
{
	enum ScanCode
	{
		Scan_NoEvent,

		Scan_A = 4,
		Scan_B,
		Scan_C,
		Scan_D,
		Scan_E,
		Scan_F,
		Scan_G,
		Scan_H,
		Scan_I,
		Scan_J,
		Scan_K,
		Scan_L,
		Scan_M,
		Scan_N,
		Scan_O,
		Scan_P,
		Scan_Q,
		Scan_R,
		Scan_S,
		Scan_T,
		Scan_U,
		Scan_V,
		Scan_W,
		Scan_X,
		Scan_Y,
		Scan_Z,

		Scan_1 = 30,
		Scan_2,
		Scan_3,
		Scan_4,
		Scan_5,
		Scan_6,
		Scan_7,
		Scan_8,
		Scan_9,
		Scan_0,

		Scan_Exclamation = 30,
		Scan_At,
		Scan_Number,
		Scan_Dollar,
		Scan_Percent,
		Scan_Caret,
		Scan_Ampersand,
		Scan_Asterisk,
		Scan_ParenthesisLeft,
		Scan_ParenthesisRight,

		Scan_Return = 41,
		Scan_Escape,
		Scan_Backspace,
		Scan_Tab,
		Scan_Space,

		Scan_Minus = 45,
		Scan_Equal,
		Scan_BracketLeft,
		Scan_BracketRight,
		Scan_Backslash,
		Scan_NUS_Backslash,

		Scan_Underscore = 45,
		Scan_Plus,
		Scan_CurlyBracketLeft,
		Scan_CurlyBracketRight,
		Scan_VerticalBar,

		Scan_Semicolon = 51,
		Scan_Apostrophe,
		Scan_Grave,
		Scan_Comma,
		Scan_Period,
		Scan_Slash,

		Scan_Colon = 51,
		Scan_Quotation,
		Scan_Tilde,
		Scan_LessThan,
		Scan_GreaterThan,
		Scan_Question,

		Scan_CapsLock = 57,
		Scan_F1,
		Scan_F2,
		Scan_F3,
		Scan_F4,
		Scan_F5,
		Scan_F6,
		Scan_F7,
		Scan_F8,
		Scan_F9,
		Scan_F10,
		Scan_F11,
		Scan_F12,

		Scan_PrintScreen = 70,
		Scan_ScrollLock,
		Scan_Break,
		Scan_Pause = Scan_Break,

		Scan_Insert = 73,
		Scan_Home,
		Scan_PageUp,
		Scan_Delete,
		Scan_End,
		Scan_PageDown,
		Scan_Right,
		Scan_Left,
		Scan_Down,
		Scan_Up,

		Scan_NumLock = 83,
		Scan_KP_Slash,
		Scan_KP_Asterisk,
		Scan_KP_Minus,
		Scan_KP_Plus,
		Scan_KP_Enter,

		Scan_KP_1 = 89,
		Scan_KP_2,
		Scan_KP_3,
		Scan_KP_4,
		Scan_KP_5,
		Scan_KP_6,
		Scan_KP_7,
		Scan_KP_8,
		Scan_KP_9,
		Scan_KP_0,
		Scan_KP_Period,
		Scan_NUS_Slash,

		Scan_KP_End = 89,
		Scan_KP_Down,
		Scan_KP_PageDown,
		Scan_KP_Left,
		Scan_KP_Right = 94,
		Scan_KP_Home,
		Scan_KP_Up,
		Scan_KP_PageUp,
		Scan_KP_Insert,
		Scan_KP_Delete,

		Scan_Application = 101,
		Scan_KB_Power,
		Scan_KP_Equal,
		Scan_F13,
		Scan_F14,
		Scan_F15,
		Scan_F16,
		Scan_F17,
		Scan_F18,
		Scan_F19,
		Scan_F20,
		Scan_F21,
		Scan_F22,
		Scan_F23,
		Scan_F24,

		Scan_KB_Execute = 116,
		Scan_KB_Help,
		Scan_KB_Menu,
		Scan_KB_Select,
		Scan_KB_Stop,
		Scan_KB_Again,
		Scan_KB_Undo,
		Scan_KB_Cut,
		Scan_KB_Copy,
		Scan_KB_Paste,
		Scan_KB_Find,
		Scan_KB_Mute,
		Scan_KB_VolumeUp,
		Scan_KB_VolumeDown,
		Scan_KB_LockingCapsLock,
		Scan_KB_LockingNumLock,
		Scan_KB_LockingScrollLock,
		Scan_KP_Comma, //- Brazilian Keypad Period -
		Scan_KB_Equal,

		Scan_KB_International1 = 135, //- Ro -
		Scan_KB_International2, //- Katakana/Hiragana -
		Scan_KB_International3, //- Yen -
		Scan_KB_International4, //- Henkan -
		Scan_KB_International5, //- Muhenkan -
		Scan_KB_International6, //- PC9800 Keypad Comma -
		Scan_KB_International7,
		Scan_KB_International8,
		Scan_KB_International9,

		Scan_KB_Langauge1 = 144, //- Hanguel/English -
		Scan_KB_Langauge2, //- Hanja -
		Scan_KB_Langauge3, //- Katakana -
		Scan_KB_Langauge4, //- Hiragana -
		Scan_KB_Langauge5, //- Zenkaku/Hankaku -
		Scan_KB_Langauge6,
		Scan_KB_Langauge7,
		Scan_KB_Langauge8,
		Scan_KB_Langauge9,

		Scan_KB_AlternateErase = 153,
		Scan_KB_SystemRequest,
		Scan_KB_Cancel,
		Scan_KB_Clear,
		Scan_KB_Prior,
		Scan_KB_Return,
		Scan_KB_Seperator,
		Scan_KB_Out,
		Scan_KB_Oper,
		Scan_KB_ClearAgain,
		Scan_KB_CrSelProps,
		Scan_KB_ExSel,

		Scan_KP_00 = 176,
		Scan_KP_000,
		Scan_KP_ThousandsSeperator,
		Scan_KP_DecimalSeperator,
		Scan_KP_CurrencyUnit,
		Scan_KP_CurrencySubUnit,
		Scan_KP_ParenthesisLeft,
		Scan_KP_ParenthesisRight,
		Scan_KP_CurlyBracketLeft,
		Scan_KP_CurlyBracketRight,
		Scan_KP_Tab,
		Scan_KP_Backspace,
		Scan_KP_A,
		Scan_KP_B,
		Scan_KP_C,
		Scan_KP_D,
		Scan_KP_E,
		Scan_KP_F,
		Scan_KP_XOR,
		Scan_KP_Caret,
		Scan_KP_Percent,
		Scan_KP_LessThan,
		Scan_KP_GreaterThan,
		Scan_KP_Ampersand,
		Scan_KP_DoubleAmpersand,
		Scan_KP_VerticalBar,
		Scan_KP_DoubleVerticalBar,
		Scan_KP_Colon,
		Scan_KP_Number,
		Scan_KP_Space,
		Scan_KP_At,
		Scan_KP_Exclamation,
		Scan_KP_MemoryStore,
		Scan_KP_MemoryRecall,
		Scan_KP_MemoryClear,
		Scan_KP_MemoryAdd,
		Scan_KP_MemorySubtract,
		Scan_KP_MemoryMultiply,
		Scan_KP_MemoryDivide,
		Scan_KP_PlusMinus,
		Scan_KP_Clear,
		Scan_KP_ClearEntry,
		Scan_KP_Binary,
		Scan_KP_Octal,
		Scan_KP_Decimal,
		Scan_KP_Hexadecimal,

		Scan_ControlLeft = 224,
		Scan_ShiftLeft,
		Scan_AlternativeLeft,
		Scan_GUILeft,
		Scan_ControlRight,
		Scan_ShiftRight,
		Scan_AlternativeRight,
		Scan_GUIRight
	};
}

#endif
