function(ce_library_module TARGET INCLUDE SRC INC RES LIB DEPENDS)
	add_library(${TARGET} STATIC ${SRC} ${INC} ${RES})
	set_target_properties(${TARGET} PROPERTIES LINKER_LANGUAGE CXX)
	set_target_properties(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/lib)
	set_target_properties(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE ${PROJECT_SOURCE_DIR}/lib)
	set_target_properties(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG ${PROJECT_SOURCE_DIR}/lib)
	set_target_properties(${TARGET} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/lib)
	set_target_properties(${TARGET} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${PROJECT_SOURCE_DIR}/lib)
	set_target_properties(${TARGET} PROPERTIES ARCHIVE_OUTPTU_DIRECTORY_DEBUG ${PROJECT_SOURCE_DIR}/lib)
	set_target_properties(${TARGET} PROPERTIES DEBUG_POSTFIX -d)
	target_include_directories(${TARGET} PUBLIC ${INCLUDE})
	target_Link_libraries(${TARGET} ${LIB})
	if(DEPENDS)
		add_dependencies(${TARGET} ${DEPENDS})
	endif()
endfunction()

function(ce_sample TARGET INCLUDE SRC INC RES LIB DEPENDS)
	add_executable(${TARGET} ${SRC})
	set_target_properties(${TARGET} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/samples/bin)
	set_target_properties(${TARGET} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PROJECT_SOURCE_DIR}/samples/bin)
	set_target_properties(${TARGET} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PROJECT_SOURCE_DIR}/samples/bin)
	set_target_properties(${TARGET} PROPERTIES DEBUG_POSTFIX -d)
	target_include_directories(${TARGET} PUBLIC ${INCLUDE})
	target_link_libraries(${TARGET} ${LIB})
	if(DEPENDS)
		add_dependencies(${TARGET} ${DEPENDS})
	endif()
endfunction()
